services:
  db:
    image: postgres:17
    healthcheck:
      test: pg_isready -U myuser -d Freezer
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: Freezer